spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./testdb
    username: sa
    password: sa
  jpa:
    show-sql: false

logging:
  level:
    web: INFO
    org.hibernate.SQL: DEBUG