apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-postgres
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "helm.name" . }}-postgres
